Implement invoice creation with unit tests
ahmadiyyanigeria/chanda-backend pull request #37
Opened 2024-07-27 12:29 UTC by usman1607

2024-07-27 15:10 UTC, yusufadeyemi requested changes

2024-07-27 15:10 UTC, yusufadeyemi commented on src/API/Controllers/InvoiceController.cs
> +        [HttpPost("Create")]
The name Create for this endpoint is not restful 
I think 
POST /invoices  is good
Not 
POST /invoices/create

2024-07-27 15:10 UTC, yusufadeyemi commented on src/API/Controllers/InvoiceController.cs
> +        public async Task<IActionResult> CretateInvoice([FromBody] CreateInvoice.Command command)
Using CreateInvoice.Command as the input dto for  a controller action is it right. The command might require more details than what the controller accept. Let us have dtos

2024-07-27 15:10 UTC, yusufadeyemi commented on src/Application/Commands/CreateInvoice.cs
> +                    throw new DomainException("Initiator not recorgnised", ExceptionCodes.MemberNotFound.ToString(), 403);
This can not be domain exception. It should be an application exception. Domain exceptions are thrown in the domain layer. Also domain exception don't use http status code.

2024-07-27 15:10 UTC, yusufadeyemi commented on src/Application/Commands/CreateInvoice.cs
> +                            invoiceItem.UpdateAmount(subTotalAmount);
Subtotal for an invoice should not be updated from outside. The logic should be encapsulated inside the domain entity. Read more on DDD

2024-07-27 15:10 UTC, yusufadeyemi commented on src/Application/Commands/CreateInvoice.cs
> +        public class CommandValidator : AbstractValidator<Command>
This validator class can be in separate file in folders for all validators. SRP and SOC (separation of concerns)

2024-07-28 06:00 UTC, yusufadeyemi approved these changes

2024-07-28 06:19 UTC, YahyaOlalekan approved these changes

2024-07-28 06:19 UTC, merged